CREATE TABLE IF NOT EXISTS USER (username TEXT PRIMARY KEY NOT NULL, password TEXT NOT NULL, level TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ITEM (id INTEGER PRIMARY KEY NOT NULL, name TEXT NOT NULL, owner TEXT NOT NULL, alert TEXT NOT NULL);
